spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  signerKey: ${JWT_SIGNER_KEY}